import React from 'react';
import type { Metadata } from 'next';

import { BodyWrapper } from '@/components/context';

import 'bootstrap-icons/font/bootstrap-icons.css';
import '@/styles/globals.css';

export const metadata: Metadata = {
	title: 'Next.js Boilerplate',
	description: 'Generated by Next.js Boilerplate'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return <BodyWrapper>{children}</BodyWrapper>;
}
