name: CI/CD Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  push:
    branches:
      - main
      - develop

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dangoslen/changelog-enforcer@v2
        with:
          changeLogPath: 'CHANGELOG.md'
          skipLabels: 'Trivial'

  build:
    runs-on: ubuntu-latest
    needs: changelog

    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear dependencies cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Building project
        run: npm run build

  deploy-preview:
    runs-on: ubuntu-latest
    needs: [changelog, build]

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN_GITHUB }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN_GITHUB }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN_GITHUB }}
